export const clinicsEN = {
    "Cardiology and Vascular Disease - قلب وأوعية دموية": "Cardiology and Vascular Disease",
    "Chest and Respiratory - صدر وجهاز تنفسي": "Chest and Respiratory",
    "Dentistry - أسنان": "Dentistry",
    "Dermatology - جلدية": "Dermatology",
    "Diabetes - سكر": "Diabetes",
    "Dietitian and Nutrition - تخسيس وتغذية": "Dietitian and Nutrition",
    "Ear, Nose and Throat - أنف وأذن وحنجرة": "Ear, Nose and Throat",
    "Fertility - تناسلية": "Fertility",
    "Gastroenterology - جهاز هضمي": "Gastroenterology",
    "General Surgery - جراحة عامة": "General Surgery",
    "Hepatology - كبد": "Hepatology",
    "Internal Medicine - باطنة": "Internal Medicine",
    "Nephrology - كلى": "Nephrology",
    "Neurology - مخ وأعصاب": "Neurology",
    "Obstetrics and Gynecology - نساء وتوليد": "Obstetrics and Gynecology",
    "Oncology - أورام": "Oncology",
    "Ophthalmology - عيون": "Ophthalmology",
    "Orthopedics - عظام": "Orthopedics",
    "Pediatrics and New Born - أطفال وحديثي الولادة": "Pediatrics and New Born",
    "Phoniatrics - نطق وتخاطب": "Phoniatrics",
    "Physiotherapy - علاج طبيعي": "Physiotherapy",
    "Plastic Surgery - جراحة تجميلية": "Plastic Surgery",
    "Psychiatry - نفسية":  "Psychiatry",
    "Spinal - عمود فقري": "Spinal",
    "Urology - مسالك بولية": "Urology"
}

export const clinicsAR = {
    "Cardiology and Vascular Disease - قلب وأوعية دموية" : "قلب وأوعية دموية",
    "Chest and Respiratory - صدر وجهاز تنفسي": "صدر وجهاز تنفسي",
    "Dentistry - أسنان" : "أسنان",
    "Dermatology - جلدية" : "جلدية",
    "Diabetes - سكر" : "سكر",
    "Dietitian and Nutrition - تخسيس وتغذية" :"تخسيس وتغذية",
    "Ear, Nose and Throat - أنف وأذن وحنجرة" :"أنف وأذن وحنجرة",
    "Fertility - تناسلية" :"تناسلية",
    "Gastroenterology - جهاز هضمي" :"جهاز هضمي",
    "General Surgery - جراحة عامة" :"جراحة عامة",
    "Hepatology - كبد" :"كبد",
    "Internal Medicine - باطنة" :" باطنة",
    "Nephrology - كلى" :"كلى",
    "Neurology - مخ وأعصاب" :"مخ وأعصاب",
    "Obstetrics and Gynecology - نساء وتوليد" :"نساء وتوليد",
    "Oncology - أورام" :" أورام",
    "Ophthalmology - عيون" :"عيون",
    "Orthopedics - عظام" :"عظام",
    "Pediatrics and New Born - أطفال وحديثي الولادة" :"أطفال وحديثي الولادة",
    "Phoniatrics - نطق وتخاطب" :"نطق وتخاطب",
    "Physiotherapy - علاج طبيعي" :"علاج طبيعي",
    "Plastic Surgery - جراحة تجميلية" :"جراحة تجميلية",
    "Psychiatry - نفسية" :"نفسية",
    "Spinal - عمود فقري" :"عمود فقري",
    "Urology - مسالك بولية" :"مسالك بولية"
}