import React from "react";
import { connect } from "react-redux";
import { addClinic } from "../../Redux/actions/clinics";

const AddDataToRedux = (props) => {
  const doctors = [
    {
      avatar: "AH",
      name: "Adel Shakel",
      specalist: "elNa7o",
      rating_total: 5,
      hospital: "Hanty Canty",
      waiting: "10 minutes",
      price: 300,
      callus: "16370",
      avaliabledate1: "Today 5:40 pm",
      avaliabledate2: "Tomorrow 5:40 pm",
      avaliabledate3: "Tomorrow 5:40 pm",
    },
    {
      avatar: "RS",
      name: "Rana Elsaeed",
      specalist: "Cardiology",
      rating_total: 5,
      hospital: "Daar EL-FOUAD",
      waiting: "10 minutes",
      price: 350,
      callus: "16370",
      avaliabledate1: "Today 2:00 pm",
      avaliabledate2: "Tomorrow 1:00 pm",
      avaliabledate3: "Tomorrow 3:00 pm",
    },
    {
      avatar: "MA",
      name: "Mariem Ahmed",
      specalist: "Cardiology",
      rating_total: 5,
      hospital: "Daar EL-FOUAD",
      waiting: "60 minutes",
      price: 150,
      callus: "16370",
      avaliabledate1: "Today 2:00 pm",
      avaliabledate2: "Tomorrow 1:00 pm",
      avaliabledate3: "Tomorrow 3:00 pm",
    },
    {
      avatar: "MS",
      name: "Mostafa Elsaeed",
      specalist: "Cardiology",
      rating_total: 5,
      hospital: "Daar EL-FOUAD",
      waiting: "20 minutes",
      price: 350,
      callus: "16370",
      avaliabledate1: "Today 2:00 pm",
      avaliabledate2: "Tomorrow 1:00 pm",
      avaliabledate3: "Tomorrow 3:00 pm",
    },
    {
      avatar: "MG",
      name: "Micheal George",
      specalist: "Cardiology",
      rating_total: 5,
      hospital: "Daar EL-FOUAD",
      waiting: "20 minutes",
      price: 400,
      callus: "16370",
      avaliabledate1: "Today 2:00 pm",
      avaliabledate2: "Tomorrow 1:00 pm",
      avaliabledate3: "Tomorrow 3:00 pm",
    },
    {
      avatar: "I",
      name: "isis",
      specalist: "Cardiology",
      rating_total: 5,
      hospital: "Daar EL-FOUAD",
      waiting: "10 minutes",
      price: 350,
      callus: "16370",
      avaliabledate1: "Today 2:00 pm",
      avaliabledate2: "Tomorrow 1:00 pm",
      avaliabledate3: "Tomorrow 3:00 pm",
    },
    {
      avatar: "YA",
      name: "Youssef Ahmed",
      specalist: "Cardiology",
      rating_total: 4,
      hospital: "Daar EL-FOUAD",
      waiting: "15 minutes",
      price: 300,
      callus: "16370",
      avaliabledate1: "Today 2:00 pm",
      avaliabledate2: "Tomorrow 1:00 pm",
      avaliabledate3: "Tomorrow 3:00 pm",
    },
    {
      avatar: "AS",
      name: "Amani Elsaid",
      specalist: "Cardiology",
      rating_total: 5,
      hospital: "Daar El fouad",
      waiting: "10 minutes",
      price: 350,
      callus: "16370",
      avaliabledate1: "Today 2:00 pm",
      avaliabledate2: "Tomorrow 1:00 pm",
      avaliabledate3: "Tomorrow 3:00 pm",
    },
    {
      avatar: "CM",
      name: "Christina Mlak",
      specalist: "Cardiology",
      rating_total: 3,
      hospital: "Daar EL-FOUAD",
      waiting: "10 minutes",
      price: 150,
      callus: "16370",
      avaliabledate1: "Today 2:00 pm",
      avaliabledate2: "Tomorrow 1:00 pm",
      avaliabledate3: "Tomorrow 3:00 pm",
    },
  ];
  return(
    <div style = {{height: "0px", width: "0px"}}>
      {doctors.map((doctor) => {props.dispatch(addClinic(doctor));})}
    </div>
  );
}
export default connect()(AddDataToRedux);