export const ServicesEN = {
    "Blood Test - تحليل دم": "Blood Analysis",
    "Heart Echo - رسم قلب": "Heart Echo",
    "X-rays - أشعة سينية": "X-rays",
    "Blood -اكياس دم":"Blood",
    "Incubation - حضانة":"Incubation",
    "Acu room - غرفة عناية مركزة":"Acu room",
    "Quarantine room - غرفة الحجر الصحي":"Quarantine room",
    "Oxygen tube - انبوبة اكسجين":"Oxygen tube",
    "Dialysis - غسيل كلوي":"Dialysis",
    'ALbumin - الألبومين': 'ALbumin',
    'ALk. Phos - ألك. فوس': 'ALk. Phos',
    'BUN - BUN': 'BUN',
    'Bil. (Direct) - بيل. (مباشر)': 'Bil. (Direct)',
    'Bill. (Total) - بيل. (مجموع)': 'Bill. (Total)',
    'Bl. Glucose (2hrs) - Bl. الجلوكوز (2 ساعة)': 'Bl. Glucose (2hrs)',
    'Bl. Glucose (Fasting) - Bl. الجلوكوز (الصيام)': 'Bl. Glucose (Fasting)',
    'Bl. Glucose (Random) - Bl. الجلوكوز (عشوائي)': 'Bl. Glucose (Random)',
    'Bleeding Time - وقت النزيف': 'Bleeding Time',
    'CBC - صورة دم': 'CBC',
    'Calcium (total) - كالسيوم (إجمالي)': 'Calcium (total)',
    'Cholesterol - كوليسترول': 'Cholesterol',
    'Clotting Time - Clotting Time': 'Clotting Time',
    'Creatinine - كرياتينين': 'Creatinine',
    'D_Dimer - د_ديمر': 'D_Dimer',
    'ESR - سرعة ترسيب': 'ESR',
    'Gamma GT - جاما جي تي': 'Gamma GT',
    'Glycosylated Hb (HbA1c) - الهيموجلوبين الغليكوزيلا': 'Glycosylated Hb (HbA1c)',
    'HDL - اتش دى ال': 'HDL',
    'LDL - ال دى ال': 'LDL',
    'Magnesium - المغنيسيوم': 'Magnesium',
    'Microalbumin in Urine - الألبومين المِكروي ف البول': 'Microalbumin in Urine',
    'Microalbumin(MAO) - الألبومين المِكروي (MAO)': 'Microalbumin(MAO) ',
    'PT - بى تى': 'PT',
    'PTT - بى تى تى': 'PTT',
    'Phosphrous - فوسفور': 'Phosphrous',
    'Potassium(K) - البوتاسيوم': 'Potassium(K)',
    'S. Ferritin - اس. فيريتين': 'S.Ferritin',
    'S. Iron - اس. الحديد': 'S.Iron',
    'SGOT (AST) - SGOT (AST)': 'SGOT (AST)',
    'SGPT (ALT) - SGPT (ALT)': 'SGPT (ALT)',
    'Sodium (Na) - الصوديوم': 'Sodium (Na)',
    'Total Proteins - إجمالي البروتينات': 'Total Proteins',
    'Triglycerides - الدهون الثلاثية': 'Triglycerides',
    'Urea - اليوريا': 'Urea',
    'Uric Acid - حمض اليوريك': 'Uric Acid',
    'PCR - PCR': 'PCR'
}
export const ServicesAR={
    "Blood Test - تحليل دم" :" تحليل دم",
    "Heart Echo - رسم قلب" :"رسم قلب",
    'X-rays - أشعة سينية': 'أشعة سينية',
    "Blood - اكياس دم":"اكياس دم",
    "Incubation - حضانة":"حضانة",
    "Acu room - غرفة عناية مركزة":" غرفة عناية مركزة",
    "Quarantine room - غرفة الحجر الصحي":" غرفة الحجر الصحي",
    "Oxygen tube - انبوبة اكسجين":" انبوبة اكسجين",
    "Dialysis - غسيل كلوي":"غسيل كلوي",
    'ALbumin - الألبومين':  'الألبومين',
    'ALk. Phos - ألك. فوس': 'ALk. Phos',
    'BUN - BUN': 'BUN',
    'Bil. (Direct) - بيل. (مباشر)': 'Bil. (Direct)',
    'Bill. (Total) - بيل. (مجموع)': 'Bill. (Total)',
    'Bl. Glucose (2hrs) - Bl. الجلوكوز (2 ساعة)': 'Bl. Glucose (2hrs)',
    'Bl. Glucose (Fasting) - Bl. الجلوكوز (الصيام)': 'Bl. Glucose (صيامى)',
    'Bl. Glucose (Random) - Bl. الجلوكوز (عشوائي)': 'Bl. Glucose (عشوائى)',
    'Bleeding Time - وقت النزيف': 'Bleeding Time',
    'CBC - صورة دم': 'صورة دم',
    'Calcium (total) - كالسيوم (إجمالي)': 'كالسيوم (إجمالي)',
    'Cholesterol - كوليسترول': 'كوليسترول',
    'Clotting Time - Clotting Time': 'Clotting Time',
    'Creatinine - كرياتينين': 'كرياتينين',
    'D_Dimer - د_ديمر': 'D_Dimer',
    'ESR - سرعة ترسيب': 'سرعة ترسيب',
    'Gamma GT - جاما جي تي': 'Gamma GT',
    'Glycosylated Hb (HbA1c) - الهيموجلوبين الغليكوزيلا': 'Glycosylated Hb (HbA1c)',
    'HDL - اتش دى ال': 'HDL',
    'LDL - ال دى ال': 'LDL',
    'Magnesium - المغنيسيوم': 'المغنيسيوم',
    'Microalbumin in Urine - الألبومين المِكروي ف البول': 'الألبومين المِكروي ف البول',
    'Microalbumin(MAO) - الألبومين المِكروي (MAO)': 'الألبومين المِكروي (MAO)',
    'PT - بى تى': 'PT',
    'PTT - بى تى تى': 'PTT',
    'Phosphrous - فوسفور': 'فوسفور',
    'Potassium(K) - البوتاسيوم': 'البوتاسيوم',
    'S. Ferritin - اس. فيريتين': 'S.Ferritin',
    'S. Iron - اس. الحديد': 'S.Iron',
    'SGOT (AST) - SGOT (AST)': 'SGOT (AST)',
    'SGPT (ALT) - SGPT (ALT)': 'SGPT (ALT)',
    'Sodium (Na) - الصوديوم': 'Sodium (Na)',
    'Total Proteins - إجمالي البروتينات':  'إجمالي البروتينات',
    'Triglycerides - الدهون الثلاثية': 'الدهون الثلاثية',
    'Urea - اليوريا': 'اليوريا',
    'Uric Acid - حمض اليوريك': 'حمض اليوريك',
    'PCR - PCR': 'PCR'
}

/*export const matchServicesAr = {
    "Blood Test - تحليل دم" :"تحليل دم",
    "Heart Echo - رسم قلب" :"رسم قلب",
    "X-rays - أشعة مقطعية" :"أشعة مقطعية"
}

export const matchServicesEn = {
    "Blood Test - تحليل دم": "Blood Test",
    "Heart Echo - رسم قلب": "Heart Echo",
    "X-rays - أشعة مقطعية": "X-rays"
}*/